- name: restart sshd
  ansible.builtin.service:
    name: sshd
    state: restarted

- name: restart cpufrequtils
  ansible.builtin.service:
    name: cpufrequtils
    state: restarted

- name: restart sssd
  ansible.builtin.service:
    name: sssd
    state: restarted

- name: daemon-reload
  ansible.builtin.systemd:
    daemon_reload: yes

- name: update ca certificates
  ansible.builtin.shell: update-ca-certificates
